// Runs before `vite dev` and `vite build`; writes src/generated/mcp-version.ts
// from the live npm registry. On any failure it exits 0 without touching files,
// so the committed fallback version stays in place.
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";

const PACKAGE = "domain-check-skills-mcp";
const OUT = resolve("src/generated/mcp-version.ts");
const LLMS = resolve("public/llms.txt");

async function main() {
  const res = await fetch(`https://registry.npmjs.org/${PACKAGE}`, {
    headers: { accept: "application/json" },
  });
  if (!res.ok) throw new Error(`registry responded ${res.status}`);

  const json = (await res.json()) as { "dist-tags"?: { latest?: string } };
  const version = json["dist-tags"]?.latest;
  if (!version || !/^\d+\.\d+\.\d+/.test(version)) throw new Error("no valid latest version");

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(
    OUT,
    `// AUTO-GENERATED by scripts/generate-mcp-version.ts — do not edit by hand.\nexport const MCP_VERSION = "${version}";\n`,
  );

  const llms = readFileSync(LLMS, "utf8");
  const patched = llms.replace(
    /(`domain-check-skills-mcp` \(npm, v)\d+\.\d+\.\d+/g,
    `$1${version}`,
  );
  if (patched !== llms) writeFileSync(LLMS, patched);

  console.log(`mcp-version.ts written (v${version})`);
}

main().catch((err) => {
  console.warn(`generate-mcp-version: skipped (${(err as Error).message})`);
  process.exit(0);
});
