// Runs before `vite dev` and `vite build`, ahead of the sitemap. Writes the
// price snapshot the /tld pages are prerendered from (src/generated/tld-prices.json)
// and the footer's link list (src/generated/tld-links.ts).
//
// Prices: registrar_prices over the public REST endpoint (RLS lets anyone read).
// RDAP facts: the edge pipeline's FAST_RDAP table and IANA's bootstrap file.
// The snapshot has no timestamp of its own, so unchanged prices leave the file
// byte-identical. On any failure it keeps the committed snapshot and exits 0.
import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import {
  PRICE_COLUMNS,
  footerTlds,
  parseFastRdap,
  parseIanaBootstrap,
  snapshotFromRows,
  type RawPriceRow,
  type TldSnapshot,
} from "../src/lib/tldPages";

const SNAPSHOT = resolve("src/generated/tld-prices.json");
const LINKS = resolve("src/generated/tld-links.ts");
const PIPELINE = resolve("supabase/functions/_shared/pipeline.ts");

function env(name: string): string | undefined {
  if (process.env[name]) return process.env[name];
  const file = resolve(".env");
  if (!existsSync(file)) return undefined;
  const line = readFileSync(file, "utf8")
    .split(/\r?\n/)
    .find((l) => l.startsWith(`${name}=`));
  return line?.slice(name.length + 1).trim().replace(/^["']|["']$/g, "");
}

async function fetchJson(url: string, headers: Record<string, string> = {}): Promise<unknown> {
  const res = await fetch(url, { headers, signal: AbortSignal.timeout(10_000) });
  if (!res.ok) throw new Error(`${new URL(url).host} responded ${res.status}`);
  return res.json();
}

function readSnapshot(): TldSnapshot | null {
  return existsSync(SNAPSHOT) ? (JSON.parse(readFileSync(SNAPSHOT, "utf8")) as TldSnapshot) : null;
}

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  writeFileSync(path, content);
  return true;
}

async function refreshSnapshot(): Promise<void> {
  const url = env("VITE_SUPABASE_URL");
  const key = env("VITE_SUPABASE_PUBLISHABLE_KEY");
  if (!url || !key) throw new Error("VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY not set");

  const fast = parseFastRdap(readFileSync(PIPELINE, "utf8"));
  const [rows, bootstrap] = await Promise.all([
    fetchJson(`${url}/rest/v1/registrar_prices?select=${PRICE_COLUMNS}&order=tld,registrar`, { apikey: key }) as Promise<RawPriceRow[]>,
    // Optional: without it the previous snapshot's bootstrap facts are kept.
    fetchJson("https://data.iana.org/rdap/dns.json").then(parseIanaBootstrap).catch(() => null),
  ]);
  if (!Array.isArray(rows) || rows.length === 0) throw new Error("no price rows returned");

  const previous = readSnapshot();
  const snapshot = snapshotFromRows(rows, (tld) => ({
    registryHost: fast.get(tld) ?? null,
    inIanaBootstrap: bootstrap ? bootstrap.has(tld) : (previous?.tlds.find((t) => t.tld === tld)?.inIanaBootstrap ?? null),
  }));
  const changed = writeIfChanged(SNAPSHOT, `${JSON.stringify(snapshot, null, 2)}\n`);
  console.log(`tld-prices.json ${changed ? "written" : "unchanged"} (${snapshot.tlds.length} TLDs)`);
}

function writeLinks(): void {
  const snapshot = readSnapshot();
  if (!snapshot) return;
  const content = [
    "// AUTO-GENERATED by scripts/generate-tld-prices.ts — do not edit by hand.",
    "// Kept apart from tld-prices.json so the footer (main bundle) does not pull in the price snapshot.",
    `export const TLD_PAGE_COUNT = ${snapshot.tlds.length};`,
    `export const FOOTER_TLDS: readonly string[] = ${JSON.stringify(footerTlds(snapshot))};`,
    "",
  ].join("\n");
  writeIfChanged(LINKS, content);
}

refreshSnapshot()
  .catch((err) => console.warn(`generate-tld-prices: kept the committed snapshot (${(err as Error).message})`))
  .finally(writeLinks);
